export interface StaticResourceInterface {
  id: string
  sid: string
  key: string
  metadata: object
  mimeType: string
  staticResourceType: string
  userId: string
  hash?: string
  project?: string
  driver?: string
  LOD0_url: string
  LOD0_size?: number
  LOD1_url?: string
  LOD1_size?: number
  LOD2_url?: string
  LOD2_size?: number
  LOD3_url?: string
  LOD3_size?: number
  LOD4_url?: string
  LOD4_size?: number
  LOD5_url?: string
  LOD5_size?: number
  LOD6_url?: string
  LOD6_size?: number
  LOD7_url?: string
  LOD7_size?: number
  LOD8_url?: string
  LOD8_size?: number
  LOD9_url?: string
  LOD9_size?: number
  LOD10_url?: string
  LOD10_size?: number
  LOD11_url?: string
  LOD11_size?: number
  LOD12_url?: string
  LOD12_size?: number
  LOD13_url?: string
  LOD13_size?: number
  LOD14_url?: string
  LOD14_size?: number
  LOD15_url?: string
  LOD15_size?: number
  LOD16_url?: string
  LOD16_size?: number
  LOD17_url?: string
  LOD17_size?: number
  attribution?: string
  licensing?: string
  tags?: string[]
}
